In [1]:
import numpy as np
A = np.arange(0,15,2)
print(A)


[ 0  2  4  6  8 10 12 14]


In [5]:
print(A.shape)
for i in range(A.size):
    print("A[{}] : {}".format(i, A[i]))

(8,)
A[0] : 0
A[1] : 2
A[2] : 4
A[3] : 6
A[4] : 8
A[5] : 10
A[6] : 12
A[7] : 14


In [24]:
import numpy as np
A = np.arange(12).reshape(3,4)
print(A)
print("A.ndim :",A.ndim)
print(A.shape, A.shape[0],A.shape[1])
for i in range(A.shape[0]):
    for j in range(A.shape[1]):
        print("A[{0}][{1}] : {2:2d}".format(i,j,A[i][j]), end = " ")
    print()

for i in range(A.shape[0]):
    print("A[{}] : {}".format(i, A[i]))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
A.ndim : 2
(3, 4) 3 4
A[0][0] :  0 A[0][1] :  1 A[0][2] :  2 A[0][3] :  3 
A[1][0] :  4 A[1][1] :  5 A[1][2] :  6 A[1][3] :  7 
A[2][0] :  8 A[2][1] :  9 A[2][2] : 10 A[2][3] : 11 
A[0] : [0 1 2 3]
A[1] : [4 5 6 7]
A[2] : [ 8  9 10 11]
