# Numpy 설치
- 파이썬으로 수치계산을 하기 위한 라이브러리  
- 다차원 배열을 효율적으로 구현한 Numpy배열간 빠른 연산을 할 수 있는 루틴 제공  
**pip install numpy**  
**conda install numpy**

In [1]:
import numpy as np

----
### 리스트 : 여러 테이터 타입의 테이터 원소를 가질수 있음
### Numpy : 단일 테이터 타입의 테이터 원소를 가질수 있음

In [4]:
import numpy as np
A = np.array([1,2,3])

In [5]:
A

array([1, 2, 3])

In [8]:
A = [1,2,3]
B = [-1,-2,-3]
C = []
for a, b in zip(A,B):
    C.append(A+B)
print(C)

[[1, 2, 1, -1, -2, -3], [1, 2, 1, -1, -2, -3], [1, 2, 1, -1, -2, -3]]


In [11]:
import numpy as np
A = np.array([1,2,3])
B = np.array([-1,-2,-3])
C = A+B
print(C)

[0 0 0]


In [12]:
A

array([1, 2, 3])

In [13]:
len(A)

3

In [14]:
type(A[0])

numpy.int32

In [15]:
import numpy as np
A = np.array([1,2,3])
B = np.array([-1,-2,-3])
C = A+B
print(C)

[0 0 0]


In [18]:
import numpy as numpy
a=np.array([0.1,0.2,0.3])
print(a)
print(a.dtype)
print(type(a[0]))

[0.1 0.2 0.3]
float64
<class 'numpy.float64'>


In [19]:
b=np.array([1,2,3])
print(b)
print(b.dtype)
print(type(b[0]))

[1 2 3]
int32
<class 'numpy.int32'>


In [20]:
c=np.array([1,2,3], dtype=np.float64)

In [21]:
print(c)
print(c.dtype)

[1. 2. 3.]
float64


In [22]:
c=np.array([1.,2.,3.])

In [23]:
print(c)
print(c.dtype)

[1. 2. 3.]
float64


In [24]:
d=np.array([1.1,2.2,3.3,4.7])
print(d.dtype)

float64


- astype(자료형)으로 데이터 타입 변환

In [27]:
print(e)

[1 2 3 4]


In [25]:
e=d.astype(np.int32)
print(e.dtype)

int32


----
## - numpy.ndarray  
- numpy 배열의 타입은 numpy.ndarray 클래스임

In [29]:
A=np.array([[1,2,3],[4,5,6]])
print(A)
print(type(A))

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


----
## - ndarray.ndim  
- 배열을 구성하는 차원의 개수

In [31]:
A=np.array([[1,2,3],[4,5,6]])
print(A.ndim)

2


In [33]:
B=np.array([1,2,3])
print(B.ndim)

1


In [36]:
C=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(C.ndim)

3


----
## - ndarray.shape  
- 배열을 구성하는 차원의 개수와 차원별 크리를 튜플로 나타냄

In [37]:
A=np.array([[1,2,3],[4,5,6]])
print(A.ndim)
print(A.shape)

2
(2, 3)


In [38]:
B=np.array([1,2,3])
print(B.ndim)
print(B.shape)

1
(3,)


In [43]:
C=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(C.ndim)
print(C.shape)

3
(2, 2, 3)


---
## - ndarray.size  
- 배열에 있는 모든 원소의 개수(shape의 모든 )

In [46]:
A=np.array([[1,2,3],[4,5,6]])
print(A.ndim)
print(A.shape)
print(A.size)

2
(2, 3)
6


In [47]:
B=np.array([1,2,3])
print(B.ndim)
print(B.shape)
print(B.size)

1
(3,)
3


In [48]:
C=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(C.ndim)
print(C.shape)
print(C.size)

3
(2, 2, 3)
12


---
## ndarray.dtype  
- 배열원소의 데이터 타입을 나타냄
## ndarray.itemsize  
- 배열원소 하나의 바이트 크기
## ndarray.data  
- 배열원소를 실제로 저장하고 있는 버퍼

In [50]:
B=np.array([1,2,3])
print(B.dtype)
print(B.itemsize)
print(B.data)

int32
4


In [51]:
A=np.array([[1,2,3],[4,5,6]])
print(A.dtype)
print(A.itemsize)
print(A.data)

int32
4


In [53]:
C=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(C.dtype)
print(C.itemsize)
print(C.data)

int32
4


## min / max / sum / mean

In [54]:
b=np.array([1,2,3,4,5,6])
print(b.max(),end=" ")
print(b.min(),end=" ")
print(b.sum(),end=" ")
print(b.mean(),end=" ")

6 1 21 3.5

In [56]:
C=np.array([[1,2,3],[4,5,6]])
C

array([[1, 2, 3],
       [4, 5, 6]])

In [59]:
C.sum(axis = 0)

array([5, 7, 9])

In [60]:
C.sum(axis = 1)

array([ 6, 15])

In [61]:
!conda install -c conda-forge opencv

ModuleNotFoundError: No module named 'cv2'

In [ ]:
import cv2
print(cv2.__version__)

In [ ]:
import cv2

image = cv2.imread("figs/sky.jpg", cv2.IMREAD_COLOR)
cv2.imshow("Ball", image)
cv2.waitKey(0)
cv2.destroyAllWindows()